#' Write conformance findings to a file
#'
#' Saves the result of [check_study()] to CSV or Excel, so findings can be
#' shared with people who don't use R, tracked in a spreadsheet, or attached
#' to a data-review document.
#'
#' Both tables are always written, never just the findings. A short findings
#' table can mean clean data, or it can mean many rules were skipped, and
#' those two situations look identical if the skipped table is dropped:
#'
#' * **Excel** (`.xlsx`) — one workbook, two sheets: `findings` and `skipped`.
#' * **CSV** (`.csv`) — two files, since CSV has no notion of sheets. Findings
#'   go to `path`; skipped rules go to a sibling file with `_skipped` before
#'   the extension (`issues.csv` gives `issues_skipped.csv`).
#'
#' Excel output needs the `writexl` package. It is a `Suggests`, so if it
#' isn't installed you get a clear message telling you to install it or use
#' `.csv` instead, rather than a failure part-way through writing.
#'
#' @section Columns for tracking:
#' Three empty columns are added to the findings — `Status`, `Owner` and
#' `Notes` — for you to fill in by hand once the file is open. They exist so a
#' finding you have looked at and decided not to act on ("expected, see
#' protocol deviation log") can be recorded next to the finding itself, rather
#' than in a separate document nobody reads.
#'
#' @param result A result from [check_dataset()] or [check_study()].
#' @param path Output file path. The extension decides the format: `.xlsx`
#'   for Excel, `.csv` (or anything else) for CSV.
#' @param tracking Add the empty `Status`/`Owner`/`Notes` columns. `TRUE` by
#'   default; set `FALSE` for a file you intend to read back into R.
#' @return The paths actually written, invisibly. One element for Excel (a
#'   single workbook). For CSV, one path per file written: the findings, plus
#'   siblings for `skipped` and `about`, plus one for `truncated` when any rule
#'   flagged more records than were kept.
#' @examples
#' dir <- tempfile("coreval_study_")
#' dir.create(dir)
#' haven::write_xpt(data.frame(USUBJID = c("1", "2"), AGE = c(30, 65)), file.path(dir, "dm.xpt"))
#' study <- read_study(dir)
#' result <- check_study(study)
#'
#' out <- file.path(dir, "findings.csv")
#' written <- write_findings(result, out)
#' basename(written)
#'
#' unlink(dir, recursive = TRUE)
#' @export
write_findings <- function(result, path, tracking = TRUE) {
  if (!is.list(result) || is.null(result$findings)) {
    stop(
      "`result` must be what check_dataset() or check_study() returned, ",
      "with a `findings` element.",
      call. = FALSE
    )
  }
  findings <- data.table::as.data.table(result$findings)
  skipped <- if (is.null(result$skipped)) {
    data.table::data.table(rule_id = character(0), domain = character(0), reason = character(0))
  } else {
    data.table::as.data.table(result$skipped)
  }

  if (isTRUE(tracking)) {
    for (col in c("Status", "Owner", "Notes")) {
      findings[[col]] <- rep("", nrow(findings))
      skipped[[col]] <- rep("", nrow(skipped))
    }
  }

  truncated <- if (is.null(result$truncated)) {
    data.table::data.table()
  } else {
    data.table::as.data.table(result$truncated)
  }

  # Provenance travels WITH the file. A shared spreadsheet outlives the console
  # session that made it: whoever opens it cannot see that a rule matched a
  # million records and only a thousand were kept, or that the result was
  # filtered to one triage level before export. Without this the file reads as
  # the complete picture, which is the same trap `skipped` exists to prevent.
  about <- data.table::data.table(
    item = c(
      "generated by", "rules version", "scoped to standard",
      "checks that ran", "checks that could not run",
      "findings rows in this file", "is this a subset of the full result?",
      "rules whose records were capped", "most records a capped rule really found"
    ),
    value = as.character(c(
      paste("coreval", utils::packageVersion("coreval")),
      rules_version(),
      attr(result, "standard") %||% "not declared - rules from every standard ran",
      attr(result, "checks_run") %||% NA_integer_,
      nrow(skipped),
      nrow(findings),
      if (isTRUE(attr(result, "filtered"))) "YES - filtered before export" else "no",
      nrow(truncated),
      if (nrow(truncated) > 0) max(truncated$records_found) else 0L
    ))
  )

  if (grepl("\\.xlsx$", path, ignore.case = TRUE)) {
    if (!requireNamespace("writexl", quietly = TRUE)) {
      stop(
        "Writing Excel files needs the 'writexl' package.\n",
        "  install.packages(\"writexl\")\n",
        "Or write CSV instead by using a '.csv' path.",
        call. = FALSE
      )
    }
    sheets <- list(
      findings = as.data.frame(findings),
      skipped = as.data.frame(skipped),
      about = as.data.frame(about)
    )
    if (nrow(truncated) > 0) {
      sheets$truncated <- as.data.frame(truncated)
    }
    writexl::write_xlsx(sheets, path = path)
    return(invisible(path))
  }

  sibling <- function(suffix) {
    p <- sub("(\\.[^.]+)$", paste0("_", suffix, "\\1"), path)
    # No extension to insert before, so append rather than silently
    # overwriting the findings file with another table.
    if (identical(p, path)) paste0(path, "_", suffix) else p
  }
  skipped_path <- sibling("skipped")
  about_path <- sibling("about")

  data.table::fwrite(findings, path)
  data.table::fwrite(skipped, skipped_path)
  data.table::fwrite(about, about_path)
  written <- c(path, skipped_path, about_path)

  if (nrow(truncated) > 0) {
    truncated_path <- sibling("truncated")
    data.table::fwrite(truncated, truncated_path)
    written <- c(written, truncated_path)
  }
  invisible(written)
}
